version: '3'
services:
  hayaoshi:
    image: node:latest
    command: npm install && node index.js
    working_dir: /hayaoshi
    volumes:
    - ../:/hayaoshi
    networks:
    - proxy
    restart: always

networks:
  proxy:
    external:
      name: proxy
